# Use a base image with Node.js installed
FROM node:16

 

# Set the working directory in the container
WORKDIR /app

 

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

 

# Install dependencies
RUN npm install

 

# Copy the rest of the application files
COPY . .

 

# Expose the desired port
EXPOSE 8080

 

# Start the application
CMD [ "node", "server.js" ]
